apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bizobs-ingress
  namespace: bizobs
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: bizobs.TRAINING_SESSION_ID.dynatrace.training
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bizobs-app-service
            port:
              number: 80