apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bizobs-app-logs
  namespace: bizobs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
