apiVersion: v1
kind: ServiceAccount
metadata:
  name: bizobs-service-manager
  namespace: bizobs
  labels:
    app: bizobs
    component: service-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: bizobs
  name: bizobs-service-manager-role
  labels:
    app: bizobs
    component: service-manager
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bizobs-service-manager-binding
  namespace: bizobs
  labels:
    app: bizobs
    component: service-manager
subjects:
- kind: ServiceAccount
  name: bizobs-service-manager
  namespace: bizobs
roleRef:
  kind: Role
  name: bizobs-service-manager-role
  apiGroup: rbac.authorization.k8s.io