apiVersion: v1
kind: Service
metadata:
  name: bizobs-app-service
  namespace: bizobs
  labels:
    app: bizobs-app
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30808
    name: http
  selector:
    app: bizobs-app
